language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: just-to-do
  api_key:
    secure: hG19YmP3kcnzVOq7ldDcG5cUFi7KbTIuIhguIaC2n9ctPelzJd8MiYXe5ukYL9XISE8y96U6mpqOoDNwtLidpW+Wlkpwi+tGiU0Q2ijaRlLZ+2MLtXGepRLQZPXcOIy8kTUhy+GaMMN9MWN4prwutswazGMr6sJH84Tol5E7MUoDtaQ/eoKD/Vu8jGVzomdwqSQ5fUPKoLKn9cOAzvfJRjm9iPS1xT+1TuSLJvvntcX43qzAAiflCVx44Fa8jX7Z73g49jdavDr3fNgtOrf2PPKhakxTDGy+GznUn3ikTaAy85aopLp2e/AzpastKbgZReo1cbcLUje9+3LkMKfs6i2nfdSCut5X26epXGrgg42ic70gRs39d/2MUgfsuOIYcUJjkoPUyei5uGnP+wIl9rHMxbbBuNc3JQU0UaUJ7Sagzm62ECxTIYZMtFh6Ms6uGaq5vgGZ+NKG0nUendCLjXR2fOumHAkP1qz1s8wUNJQEiHAPyP9WOZheKhqe2+2lcO6cVNI4Ox3QQvtNTYfAAgdarsXczwVQx2diB6zqZDTlrnNwJVW1LPUwnk948mNMpd5VOnkpKCtYm6O8L0zt6o26YrPOpYFVOfyFWmZvKxey7kRG6o3rlTXVcQ/5REzo1wQngdV64hujcZVi1Cs5LJlVXON01jWqkykNRwowSHw=
