language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: just-to-do
  api_key:
    secure: dcEZNMFAlYtEJANwG1zbeVg9RNyLP33QjDn/V55qOLP0Jqr+yrpDaOXH7g09qSgvSybGkZrWZQNwHw0cLvW6TKoAR6qKWcooiickdtxKUdGT3m6o9FlSIU0yz05J55lcNOLjMG+8qB6Ve/hfHXY9y3mmsbD4rArgKkhtxc6qyrxYQIPb3R+plADlr9SLZ19dHm3/db2hjwCdkpb5OgbLiUKoKGhYJFV0KHpB+Ti6ywBC0KHWuxpXNJOfU8IsbAiW2r863th1pGv5Uak+kADGs+5S/rfjoDAIcbiZAlwgqTku8tqah5MTRerS+XbUqtXumdd62ihkeRqsddAj1tR9KCDzMbmDrcb+J3UjchhWGKUe1tidggh7R2cVh9ekMfojiSSfcxVzVmfr1YAQlaTpfI1WQDyt9RD5R/qDKtzCicy6rF+uNxLsuKGG7kD/LkDGJLfw2rS11mVpHH5qMyl0wulfCMeCde7UQq2nZTDTz9rAiCbSSnmCamuLMhwoTFZHqzp2RyHHBYZd6A+44HVb530hDhtPIMb8HCI/3PEPTtgPNXpz3P14nBImZo5pOy6KJ++rK4y2AcXij08FY+5c+fIsowLxCZGfay37qM1fIuqXL7gqg5cYsEyp8LR50tEpOD8LLpZp8V1d5PWWxcosp1Irdlb0S/peuvFXdV6LDrU=
