language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: just-to-do
  api_key:
    secure: XUhsKmwp+QKnsbKGIC54OfoVFbt65AnEDsaim0PyviLTDsmu6Qr35CdtWSaCSERdG5y0ZZDabv5oUTb2k7I5+4g84e+i2LxR4yZppeQFxVMl+BPwfNGYVUi8Yhh62y4zGw789KjbulIS4kdEdfwweLo8yY6zcpZIpFKE/Pj2FZOCc0UxnTlxyNXBPK0dZt9irAju4Eo7ElG32svHuDbT+l5nyGlq4PngugQpoZN3iBrIPiXeRdUEj1a6nvEauxCfBGTqXDUqy5tC+XZ25txPrLvpUKICGJ/r0bMXl5ZwJ8xcRZqx0BTnK+DGnkZTdGtmEpmzRofwqnORiSGVHDo54XNqNY1uwf4CvrNfsEMTg0ywL7YTor4UcVCB/o7/86HJWi33t2x+irQfmF/LipIVqjtcs9Z9kbGvpcddxNLiqCnr1aAAa4owH29RMcSskEH83ZlnD7zkKDXReQf+0VJFnEUQI8ld3wl+868wnOZtEF/r+26z5dNPhA/uE8nfOOIX94vAY+PqCJEhrcWXpf0tbOK9ObX3CVhq8l6Hc1bWUgKJX9mzqobZBASnHHmvvYkDa26P80oX33Mf998JjFOYR7VVj9C3+d0tNJ1+YD4AeBhE8BUSy5U6TVQC2VRMWNIa+tPBCBcKG+VRqMnlpf31t3p6BG8RY9bU9vGj34ZsR68=
