language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: just-to-do
  api_key:
    secure: bxiT6XFPr17F1ysPil3o5SmoIqacG0sPzWm8cN9TRqGEnBxc3+ddKToYMJzcpnPNTqAVUqn+W4VrcZcLMjQmFweyQfYq7vMwg5OqZxosFG/n2TKhz08CW8guBbXMW+VO//JLpHBDMSa+HkcnhM9GmS8jsXtF2PqKHXvxaekpHDNvHBSX0dQAI51VU2GrykqefY7KgkbNSfmmOglenwwUZ5J0xmGmsR15WkWREsZqQg4y9QKDQ11167GGDkbBh0un1Kv7VzRE+IRvunnvUNsrCu+BZLzswIZ72empr6E0r1KEYsFavVFpwwCKPwC3XCO3ndNYSX+ux4tQ57PzOLboUN0jEiBd+tonIh6gaqp6bKL+zuxQEXEN/gGkY2en9veC0/z6AecppYMlsGF4ABS4Gy24W4xpgFAGHOlw4fyjb1A8SLK/jQBkGW+wYYzNjCB51DmekeaflryD1XtvZciGXRtqZaWWhDMWyrDjK0UCNvB0q6M03ddUR5t+HNy9b+XPLF93kej6/neh7y0G929Aqwy5SBNw/njhx/4JPRmhByH+fzyUOEtUaXMWAKyOiF6mrZOYyEvRH5ZeBwD6/7qJQ7cwYgBF/LD+JnI0y/OK0Ggzi5a8Xk3LUJ4Aj4aNaIONoaX+kU3w8hgznFLS6S2MxaRBDWJIZC+DxJtqTBZyw1c=
